version: '2'
services:
  nmap:
    build: .
    image: sammascanner/nmap:v0.2
    volumes:
      - ./:/scanner
    environment:
      - TARGET=195.178.178.114
    #command: python3 /code/nmap_httprecon.py
    command: python3 /code/nmap_tlscipher.py
