services:
  nmap:
    build: .
    image: ghcr.io/samma-io/nmap:latest
    volumes:
      - ./out:/out
    environment:
      - TARGET=hellohippo.com
      - SAMMA_IO_SCANNER=nmap
      - SAMMA_IO_ID=1234
      - SAMMA_IO_TAGS=scanner,prod
      - SAMMA_IO_JSON={}
      - TARGET_ID=
      - WRITE_TO_FILE=true
      - PARSER=nmap
      - NATS_ENABLED=False
      - NATS_URL=nats://localhost:4222
      - NATS_SUBJECT=scans
    #command: python3 /code/nmap_httprecon.py
    command: python3 /code/nmap_tlscipher.py
