# Default values for nmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: latest

schedule: "01 * * * *"


#
# Ip ore dns name of you target.
# Every target will geta a job running
targets:
  - 10.100.0.1
  - 192.168.1.100
  - 23.11.1.11
